INSERT INTO [dead].[ExecutionStatus]
    ([GUID]
    ,[ScheduleID]
    ,[TaskID]
    ,[ServerID]	
	,[Inserted]
    ,[LastUpdate]
    ,[Status]
	,[ReturnCode])
VALUES
    (
    @GUID
    ,@ScheduleID
    ,@TaskID
    ,@ServerID
	,@Inserted
    ,@LastUpdate
    ,@Status
	,@ReturnCode);